language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

install:
  # Install composer packages, will also trigger dump-autoload
  - travis_retry composer install --no-interaction
  
script:
  - ./vendor/bin/phpunit  ./parser/
